ALTER SESSION SET CONTAINER=CDB$ROOT;
GRANT CREATE SESSION, SET CONTAINER TO c##cfltuser CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##cfltuser CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##cfltuser CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##cfltuser CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##cfltuser CONTAINER=ALL;

exit;